pipeline:
  inputs:
    conn1:
      type: connector
      value: dock1
      oneof:
        - docker
  stages:
    - name: Build and Push to Docker
      action:
        uses: account.template_with_docker_remote
        with:
          conn: <+inputs.conn1.id>
          repo: shaliniagr/todolist-random-temp
          tags: harnesstest_trigger7
