pipeline:
  stages:
    - name: Build and Push to Docker
      action:
        uses: template_with_docker
        with:
          conn: gituhb
          repo: shaliniagr/todolist-random-temp
          tags: harnesstest
