pipeline:
  inputs:
    conn1:
      type: connector
      value: gituhb
      oneOf:
        - github
  stages:
    - name: Build and Push to Docker
      action:
        uses: account.template_with_docker
        with:
          conn: <+inputs.conn1>
          repo: shaliniagr/todolist-random-temp
          tags: harnesstest